apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

namePrefix: kz-

labels:
  - pairs:
      managed-by: kustomize
    includeSelectors: true

configMapGenerator:
  - name: nginx-config
    literals:
      - GREETING=xin chao anh huy devop tuong lai

imagesn :
  - name: nginx
    newTag: 1.21.6-alpine
