apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

namePrefix: kz-

commonLabels:
  managed-by: kustomize

configMapGenerator:
  - name: nginx-config
    literals:
      - GREETING=  "xin chào anh huy devop tương lai"

images:
  - name: nginx
    newTag: 1.21.6-alpine
