apiVersion: v1
kind: Pod
metadata:
  name: liveness-failing-pod
spec:
  containers:
    - name: app
      image: busybox:1.36
      command: ["sh", "-c", "echo 'App is running...'; sleep 3600"]
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
